CREATE TABLE Person (
	ID		CHAR(9)	PRIMARY KEY,
	NAME		CHAR(20) NOT NULL,
	PHONENUM	CHAR(10) NOT NULL,
	EMAIL		CHAR(15) NOT NULL,
	ADDR		CHAR(10) NOT NULL,
	JOBTITLE	CHAR(15) ,
	PAYRATE		CHAR(5) ,
	SPECIALTY 	CHAR(10) ,
	ISEMPLOYEE	BOOL NOT NULL,
	ISCLIENT	BOOL NOT NULL
);

CREATE TABLE Appointment (
	DATE	CHAR(10) PRIMARY KEY,
	TIME	CHAR(4) PRIMARY KEY
);

CREATE TABLE Invoice (
	INVID	INT PRIMARY KEY,
	AMOUNT	DOUBLE NOT NULL,
	DATE	CHAR(10) NOT NULL
);

CREATE TABLE Schedule (
	DATE		CHAR(10) PRIMARY KEY,
	CUSTOMERS	INT NOT NULL
);

CREATE TABLE Services (
	HAIR		CHAR(10) ,
	MAKEUP		CHAR(10) ,
	MANICURES	CHAR(10) ,
	MASSAGES	CHAR(10) ,
	WAX		CHAR(10)
);

CREATE TABLE Appointment (
	DATE		CHAR(10) NOT NULL,
	TIME		CHAR(4) NOT NULL,
	CLIENTID	CHAR(9) NOT NULL,

	PRIMARY KEY (DATE),
	PRIMARY KEY (TIME),
	FOREIGN KEY (CLIENTID) REFERENCES Person(ID)
);

CREATE TABLE Invoice (
	INVID		INT NOT NULL,
	AMOUNT		DOUBLE NOT NULL,
	DATE		CHAR(10) NOT NULL,
	CLIENTID	CHAR(9) NOT NULL,

	PRIMARY KEY (INVID),
	FOREIGN KEY (CLIENTID) REFERENCES Person(ID)
);

CREATE TABLE Schedule (
	DATE		CHAR(10) NOT NULL,
	CUSTOMERS	INT NOT NULL,
	CLIENTID	CHAR(9) NOT NULL,

	PRIMARY KEY (DATE),
	FOREIGN KEY (CLIENTID) REFERENCES Person(ID)
);	

CREATE TABLE Employee (
	EMPLOYEEID	CHAR(9) NOT NULL,
	JOBTITLE	CHAR(15) NOT NULL,
	PAYRATE		CHAR(5) NOT NULL,
	SPECIALTY	CHAR(10) NOT NULL,
	SCHEDULEDATE	CHAR(10) NOT NULL,

	PRIMARY KEY (EMPLOYEEID),
	FOREIGN KEY (EMPLOYEEID) REFERENCES Person(ID),
	FOREIGN KEY (SCHEDULEDATE) REFERENCES Schedule(DATE)
);

CREATE TABLE Performs (
	EMPLOYEEID	CHAR(9) NOT NULL,
	SERVICE		CHAR(15) NOT NULL,

	PRIMARY KEY (EMPLOYEEID),
	FOREIGN KEY (EMPLOYEEID) REFERENCES Person(ID),
);

CREATE TABLE Prefers (
	CLIENTID	CHAR(9) NOT NULL,
	EMPLOYEEID	CHAR(9) NOT NULL,
	SERVICE		CHAR(15) NOT NULL,

	PRIMARY KEY (CLIENTID),
	FOREIGN KEY (CLIENTID) REFERENCES Person(ID),
	PRIMARY KEY (EMPLOYEEID),
	FOREIGN KEY (EMPLOYEEID) REFERENCES Person(ID),
);
